[package]
name = "solana-storage-proto"
version = "1.6.20"
description = "Solana Storage Protobuf Definitions"
authors = ["Solana Maintainers <maintainers@solana.com>"]
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
documentation = "https://docs.rs/solana-storage-proto"
edition = "2018"

[dependencies]
bincode = "1.2.1"
bs58 = "0.3.1"
prost = "0.8.0"
serde = "1.0.122"
serde_derive = "1.0.103"
solana-account-decoder = { path = "../account-decoder", version = "=1.6.20" }
solana-sdk = { path = "../sdk", version = "=1.6.20" }
solana-transaction-status = { path = "../transaction-status", version = "=1.6.20" }

[lib]
crate-type = ["lib"]
name = "solana_storage_proto"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies]
tonic-build = "0.5.0"
